---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ticketing
  region: us-east-1
availabilityZones:
  - us-east-1a
  - us-east-1b
managedNodeGroups:
  - name: on-demand
    labels:
      role: on-demand
    instanceType: m5.large
    desiredCapacity: 3
    volumeSize: 20
