---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: 799440659939.dkr.ecr.us-east-1.amazonaws.com/auth
          # readinessProbe:
          #   httpGet:
          #     path: /api/users/cpu/test
          #     port: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://auth-mongo-srv:27017/auth"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: auth
