# What do want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-mongo-pvc
  namespace: staging
spec:
  storageClassName: cloud-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
---
# How do we want it implemented
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-ssd
  namespace: staging
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
